name: "Feature Request"
description: "Suggest a new feature or improvement for ProxCenter"
title: "[Feature]: "
labels: ["feature-request", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature! Your ideas help make ProxCenter better for everyone.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: "Describe the feature..."
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem / Use Case
      description: What problem does this feature solve? What is your use case?
      placeholder: "I'm always frustrated when... / I need this because..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working?
      placeholder: "It would be great if ProxCenter could..."
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "I've tried... / Another approach could be..."
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Which area of ProxCenter does this relate to?
      options:
        - Infrastructure Management
        - Automation
        - Operations / Monitoring
        - Security
        - UI / UX
        - API / Backend
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical for my workflow
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mockups about the feature request.
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to help implement this feature
          required: false
