package reports

// Language represents a supported language
type Language string

const (
	LangEnglish Language = "en"
	LangFrench  Language = "fr"
)

// Translations contains all translatable strings for reports
type Translations struct {
	// Cover page
	EnterpriseReport string
	ReportPeriod     string
	Generated        string
	GeneratedBy      string
	ReportID         string

	// Section headers
	ExecutiveSummary       string
	ClustersOverview       string
	NodesDetail            string
	VirtualMachines        string
	StorageOverview        string
	AlertsSummary          string
	ActiveAlerts           string
	AlertHistory           string
	UtilizationSummary     string
	CPUUtilization         string
	MemoryUtilization      string
	InventorySummary       string
	VMInventory            string
	HardwareSpecsSummary   string
	CapacityPlanningSummary string
	CurrentCapacity        string
	Recommendations        string

	// Stats cards
	Clusters       string
	Nodes          string
	TotalVMs       string
	RunningVMs     string
	Running        string
	Stopped        string
	AvgCPU         string
	AvgMemory      string
	AvgStorage     string
	Critical       string
	Warning        string
	Info           string

	// Table headers
	ClusterName    string
	NodeName       string
	VMName         string
	Status         string
	Cores          string
	CPU            string
	Memory         string
	MemPct         string
	VCPUs          string
	VMID           string
	Node           string
	Storage        string
	Type           string
	Total          string
	Used           string
	Free           string
	Usage          string
	Severity       string
	Resource       string
	Message        string
	Count          string

	// Resource utilization
	ResourceUtilization string
	CPUUsage           string
	MemoryUsage        string
	StorageUsage       string

	// Key metrics
	KeyMetrics              string
	TotalStorageCapacity    string
	UsedStorage             string
	AverageCPUUtilization   string
	AverageMemoryUtilization string
	TotalNodes              string
	TotalCPUCores           string
	TotalMemory             string
	TotalStorage            string

	// AI Analysis
	AIPoweredInsights       string
	AIPoweredCapacityAnalysis string

	// Paragraphs
	InfraReportIntro        string
	AlertsReportIntro       string
	UtilizationReportIntro  string
	InventoryReportIntro    string
	CapacityReportIntro     string
	ShowingTopVMs           string
	ShowingRecentAlerts     string

	// Report type labels
	InfrastructureReport   string
	AlertsReport           string
	UtilizationReport      string
	InventoryReport        string
	CapacityPlanningReport string

	// Status values
	Online  string
	Offline string

	// Recommendations
	HighCPURecommendation     string
	HighMemoryRecommendation  string
	HighStorageRecommendation string
	LowUtilRecommendation     string

	// Footer
	Page string

	// Allocated
	TotalAllocatedVCPUs   string
	TotalAllocatedMemory  string
	AverageVCPUsPerVM     string
	AverageMemoryPerVM    string

	// Storage fallback
	ClusterTotal  string
	NoStorageData string
}

// GetTranslations returns translations for the specified language
func GetTranslations(lang Language) *Translations {
	switch lang {
	case LangFrench:
		return getFrenchTranslations()
	default:
		return getEnglishTranslations()
	}
}

func getEnglishTranslations() *Translations {
	return &Translations{
		// Cover page
		EnterpriseReport: "Enterprise Report",
		ReportPeriod:     "Report Period",
		Generated:        "Generated",
		GeneratedBy:      "Generated by ProxCenter Enterprise",
		ReportID:         "Report ID",

		// Section headers
		ExecutiveSummary:       "Executive Summary",
		ClustersOverview:       "Clusters Overview",
		NodesDetail:            "Nodes Detail",
		VirtualMachines:        "Virtual Machines",
		StorageOverview:        "Storage Overview",
		AlertsSummary:          "Alerts Summary",
		ActiveAlerts:           "Active Alerts",
		AlertHistory:           "Alert History",
		UtilizationSummary:     "Utilization Summary",
		CPUUtilization:         "CPU Utilization",
		MemoryUtilization:      "Memory Utilization",
		InventorySummary:       "Inventory Summary",
		VMInventory:            "Virtual Machines Inventory",
		HardwareSpecsSummary:   "Hardware Specifications Summary",
		CapacityPlanningSummary: "Capacity Planning Summary",
		CurrentCapacity:        "Current Capacity",
		Recommendations:        "Recommendations",

		// Stats cards
		Clusters:   "Clusters",
		Nodes:      "Nodes",
		TotalVMs:   "Total VMs",
		RunningVMs: "Running VMs",
		Running:    "Running",
		Stopped:    "Stopped",
		AvgCPU:     "Avg CPU",
		AvgMemory:  "Avg Memory",
		AvgStorage: "Avg Storage",
		Critical:   "Critical",
		Warning:    "Warning",
		Info:       "Info",

		// Table headers
		ClusterName: "Cluster Name",
		NodeName:    "Node",
		VMName:      "VM Name",
		Status:      "Status",
		Cores:       "Cores",
		CPU:         "CPU",
		Memory:      "Memory",
		MemPct:      "Mem %",
		VCPUs:       "vCPUs",
		VMID:        "VMID",
		Node:        "Node",
		Storage:     "Storage",
		Type:        "Type",
		Total:       "Total",
		Used:        "Used",
		Free:        "Free",
		Usage:       "Usage",
		Severity:    "Severity",
		Resource:    "Resource",
		Message:     "Message",
		Count:       "Count",

		// Resource utilization
		ResourceUtilization: "Resource Utilization",
		CPUUsage:           "CPU Usage",
		MemoryUsage:        "Memory Usage",
		StorageUsage:       "Storage Usage",

		// Key metrics
		KeyMetrics:              "Key Metrics",
		TotalStorageCapacity:    "Total Storage Capacity",
		UsedStorage:             "Used Storage",
		AverageCPUUtilization:   "Average CPU Utilization",
		AverageMemoryUtilization: "Average Memory Utilization",
		TotalNodes:              "Total Nodes",
		TotalCPUCores:           "Total CPU Cores",
		TotalMemory:             "Total Memory",
		TotalStorage:            "Total Storage",

		// AI Analysis
		AIPoweredInsights:       "AI-Powered Insights",
		AIPoweredCapacityAnalysis: "AI-Powered Capacity Analysis",

		// Paragraphs
		InfraReportIntro:       "This infrastructure report provides a comprehensive overview of your Proxmox environment for the period from %s to %s. The infrastructure consists of %d cluster(s) with a total of %d node(s) hosting %d virtual machine(s), of which %d are currently running.",
		AlertsReportIntro:      "This alerts report covers the period from %s to %s. There are currently %d active alerts requiring attention, including %d critical and %d warning level alerts.",
		UtilizationReportIntro: "This utilization report analyzes resource consumption from %s to %s. The average CPU utilization across all clusters is %.1f%%, memory utilization is %.1f%%, and storage utilization is %.1f%%.",
		InventoryReportIntro:   "This inventory report provides a complete listing of all virtual resources as of %s. The environment contains %d virtual machines across %d cluster(s), with %d currently running and %d stopped.",
		CapacityReportIntro:    "This capacity planning report provides an analysis of current resource utilization and recommendations for the period from %s to %s.",
		ShowingTopVMs:          "Showing top %d VMs by CPU usage",
		ShowingRecentAlerts:    "Showing %d most recent alerts out of %d total",

		// Report type labels
		InfrastructureReport:   "Infrastructure Report",
		AlertsReport:           "Alerts Report",
		UtilizationReport:      "Utilization Report",
		InventoryReport:        "Inventory Report",
		CapacityPlanningReport: "Capacity Planning Report",

		// Status
		Online:  "Online",
		Offline: "Offline",

		// Recommendations
		HighCPURecommendation:     "%s: High CPU utilization (%.1f%%). Consider adding more compute capacity.",
		HighMemoryRecommendation:  "%s: High memory utilization (%.1f%%). Consider adding more memory.",
		HighStorageRecommendation: "%s: High storage utilization (%.1f%%). Consider expanding storage.",
		LowUtilRecommendation:     "%s: Low overall utilization. Consider consolidating workloads.",

		// Footer
		Page: "Page %d",

		// Allocated
		TotalAllocatedVCPUs:  "Total Allocated vCPUs",
		TotalAllocatedMemory: "Total Allocated Memory",
		AverageVCPUsPerVM:    "Average vCPUs per VM",
		AverageMemoryPerVM:   "Average Memory per VM",

		// Storage fallback
		ClusterTotal:  "Cluster Total",
		NoStorageData: "No detailed storage data available.",
	}
}

func getFrenchTranslations() *Translations {
	return &Translations{
		// Cover page
		EnterpriseReport: "Rapport Enterprise",
		ReportPeriod:     "Période du rapport",
		Generated:        "Généré le",
		GeneratedBy:      "Généré par ProxCenter Enterprise",
		ReportID:         "ID du rapport",

		// Section headers
		ExecutiveSummary:       "Résumé exécutif",
		ClustersOverview:       "Vue d'ensemble des clusters",
		NodesDetail:            "Détail des noeuds",
		VirtualMachines:        "Machines virtuelles",
		StorageOverview:        "Vue d'ensemble du stockage",
		AlertsSummary:          "Résumé des alertes",
		ActiveAlerts:           "Alertes actives",
		AlertHistory:           "Historique des alertes",
		UtilizationSummary:     "Résumé de l'utilisation",
		CPUUtilization:         "Utilisation CPU",
		MemoryUtilization:      "Utilisation mémoire",
		InventorySummary:       "Résumé de l'inventaire",
		VMInventory:            "Inventaire des machines virtuelles",
		HardwareSpecsSummary:   "Résumé des spécifications matérielles",
		CapacityPlanningSummary: "Résumé de la planification de capacité",
		CurrentCapacity:        "Capacité actuelle",
		Recommendations:        "Recommandations",

		// Stats cards
		Clusters:   "Clusters",
		Nodes:      "Noeuds",
		TotalVMs:   "Total VMs",
		RunningVMs: "VMs actives",
		Running:    "Actives",
		Stopped:    "Arrêtées",
		AvgCPU:     "CPU moy.",
		AvgMemory:  "Mém. moy.",
		AvgStorage: "Stock. moy.",
		Critical:   "Critique",
		Warning:    "Avertissement",
		Info:       "Info",

		// Table headers
		ClusterName: "Nom du cluster",
		NodeName:    "Noeud",
		VMName:      "Nom de la VM",
		Status:      "Statut",
		Cores:       "Coeurs",
		CPU:         "CPU",
		Memory:      "Mémoire",
		MemPct:      "Mém %",
		VCPUs:       "vCPUs",
		VMID:        "VMID",
		Node:        "Noeud",
		Storage:     "Stockage",
		Type:        "Type",
		Total:       "Total",
		Used:        "Utilisé",
		Free:        "Libre",
		Usage:       "Usage",
		Severity:    "Sévérité",
		Resource:    "Ressource",
		Message:     "Message",
		Count:       "Nombre",

		// Resource utilization
		ResourceUtilization: "Utilisation des ressources",
		CPUUsage:           "Utilisation CPU",
		MemoryUsage:        "Utilisation mémoire",
		StorageUsage:       "Utilisation stockage",

		// Key metrics
		KeyMetrics:              "Métriques clés",
		TotalStorageCapacity:    "Capacité de stockage totale",
		UsedStorage:             "Stockage utilisé",
		AverageCPUUtilization:   "Utilisation CPU moyenne",
		AverageMemoryUtilization: "Utilisation mémoire moyenne",
		TotalNodes:              "Total des noeuds",
		TotalCPUCores:           "Total des coeurs CPU",
		TotalMemory:             "Mémoire totale",
		TotalStorage:            "Stockage total",

		// AI Analysis
		AIPoweredInsights:       "Analyse IA",
		AIPoweredCapacityAnalysis: "Analyse de capacité IA",

		// Paragraphs
		InfraReportIntro:       "Ce rapport d'infrastructure fournit une vue d'ensemble complète de votre environnement Proxmox pour la période du %s au %s. L'infrastructure comprend %d cluster(s) avec un total de %d noeud(s) hébergeant %d machine(s) virtuelle(s), dont %d sont actuellement en fonctionnement.",
		AlertsReportIntro:      "Ce rapport d'alertes couvre la période du %s au %s. Il y a actuellement %d alertes actives nécessitant une attention, dont %d critiques et %d avertissements.",
		UtilizationReportIntro: "Ce rapport d'utilisation analyse la consommation des ressources du %s au %s. L'utilisation moyenne du CPU sur tous les clusters est de %.1f%%, l'utilisation de la mémoire est de %.1f%%, et l'utilisation du stockage est de %.1f%%.",
		InventoryReportIntro:   "Ce rapport d'inventaire fournit une liste complète de toutes les ressources virtuelles au %s. L'environnement contient %d machines virtuelles réparties sur %d cluster(s), dont %d en fonctionnement et %d arrêtées.",
		CapacityReportIntro:    "Ce rapport de planification de capacité fournit une analyse de l'utilisation actuelle des ressources et des recommandations pour la période du %s au %s.",
		ShowingTopVMs:          "Affichage des %d premières VMs par utilisation CPU",
		ShowingRecentAlerts:    "Affichage des %d alertes les plus récentes sur %d au total",

		// Report type labels
		InfrastructureReport:   "Rapport d'infrastructure",
		AlertsReport:           "Rapport d'alertes",
		UtilizationReport:      "Rapport d'utilisation",
		InventoryReport:        "Rapport d'inventaire",
		CapacityPlanningReport: "Rapport de planification de capacité",

		// Status
		Online:  "En ligne",
		Offline: "Hors ligne",

		// Recommendations
		HighCPURecommendation:     "%s : Utilisation CPU élevée (%.1f%%). Envisagez d'ajouter plus de capacité de calcul.",
		HighMemoryRecommendation:  "%s : Utilisation mémoire élevée (%.1f%%). Envisagez d'ajouter plus de mémoire.",
		HighStorageRecommendation: "%s : Utilisation stockage élevée (%.1f%%). Envisagez d'étendre le stockage.",
		LowUtilRecommendation:     "%s : Faible utilisation globale. Envisagez de consolider les charges de travail.",

		// Footer
		Page: "Page %d",

		// Allocated
		TotalAllocatedVCPUs:  "Total vCPUs alloués",
		TotalAllocatedMemory: "Mémoire totale allouée",
		AverageVCPUsPerVM:    "Moyenne vCPUs par VM",
		AverageMemoryPerVM:   "Mémoire moyenne par VM",

		// Storage fallback
		ClusterTotal:  "Total cluster",
		NoStorageData: "Aucune donnée de stockage détaillée disponible.",
	}
}

// SupportedLanguages returns the list of supported languages
func SupportedLanguages() []map[string]string {
	return []map[string]string{
		{"code": "en", "name": "English"},
		{"code": "fr", "name": "Français"},
	}
}
