FROM postgres:16-alpine

RUN apk add --no-cache python3 py3-pip py3-psycopg2 su-exec gettext && \
    pip3 install --break-system-packages patroni[etcd3]==4.0.4

COPY entrypoint-patroni.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
