vrrp_script chk_proxcenter {
    script "/etc/keepalived/track_script_resolved.sh"
    interval 3
    fall 2
    rise 1
}

vrrp_instance VI_PROXCENTER {
    state BACKUP
    interface ${VIP_INTERFACE}
    virtual_router_id 51
    priority ${VRRP_PRIORITY}
    nopreempt
    advert_int 1

    unicast_src_ip ${NODE_IP}
    unicast_peer {
        ${PEER1_IP}
        ${PEER2_IP}
        ${PEER3_IP}
    }

    virtual_ipaddress {
        ${VIP}/${VIP_PREFIX} dev ${VIP_INTERFACE}
    }

    track_script {
        chk_proxcenter
    }
}
