// sudoersTemplate builds a /etc/sudoers.d/proxcenter body from the
// orchestrator allowlist. Prefixes that are not bare executables (for
// example the `for br in $(ovs-vsctl list-br)` loop) are covered by a
// scoped `/bin/sh` entry — callers render a UI warning when any such
// shell-wrapped prefix is present.

export interface AllowlistCommand {
  prefix: string
  category: string
  description: string
  usedBy: string
}

export interface AllowlistCategoryShape {
  id: string
  label: string
  description: string
  commands: AllowlistCommand[]
}

// Maps a prefix to the absolute path of its main executable. Prefixes
// not listed here fall into the shellWrappedPrefixes bucket. Add entries
// only when the exec path is stable across Debian-based PVE installs.
const executablePathByPrefix: Record<string, string> = {
  'qm unlock': '/usr/sbin/qm',
  'qm status': '/usr/sbin/qm',
  'qm create': '/usr/sbin/qm',
  'qm set': '/usr/sbin/qm',
  'qm disk import': '/usr/sbin/qm',
  'qm start': '/usr/sbin/qm',
  'qm monitor ': '/usr/sbin/qm',
  'pct unlock': '/usr/sbin/pct',
  'pct status': '/usr/sbin/pct',
  'ha-manager crm-command node-maintenance': '/usr/sbin/ha-manager',
  'nohup bash': '/usr/bin/nohup',
  'cat /tmp/.proxcenter-upgrade-status': '/usr/bin/cat',
  'echo ': '/usr/bin/echo',
  'curl ': '/usr/bin/curl',
  'qemu-img ': '/usr/bin/qemu-img',
  'timeout ': '/usr/bin/timeout',
  'rm -f /tmp/': '/usr/bin/rm',
  'which ': '/usr/bin/which',
  'pvesm ': '/usr/sbin/pvesm',
  'rbd map ': '/usr/bin/rbd',
  'rbd unmap ': '/usr/bin/rbd',
  'cat "': '/usr/bin/cat',
  "cat '": '/usr/bin/cat',
  'stat -c %s "': '/usr/bin/stat',
  "stat -c '%s' '": '/usr/bin/stat',
  'rm -f "': '/usr/bin/rm',
  'tail -c ': '/usr/bin/tail',
  'cat > "': '/usr/bin/cat',
  'mkdir -p ': '/usr/bin/mkdir',
  'export SSHPASS=': '/usr/bin/sshpass',
  'grep -q ': '/usr/bin/grep',
  'sed -i ': '/usr/bin/sed',
  'fusermount ': '/usr/bin/fusermount',
  'test -f ': '/usr/bin/test',
  'test -S ': '/usr/bin/test',
  'ls "': '/usr/bin/ls',
  "ls -1 '": '/usr/bin/ls',
  'ssh-keygen ': '/usr/bin/ssh-keygen',
  'ssh -i ': '/usr/bin/ssh',
  'aa-complain ': '/usr/sbin/aa-complain',
  'aa-enforce ': '/usr/sbin/aa-enforce',
  'apparmor_parser ': '/sbin/apparmor_parser',
  'modprobe ': '/usr/sbin/modprobe',
  'qemu-nbd ': '/usr/bin/qemu-nbd',
  'fuser ': '/usr/bin/fuser',
  'chmod ': '/usr/bin/chmod',
  'virt-v2v ': '/usr/bin/virt-v2v',
  'apt-get ': '/usr/bin/apt-get',
  'pv ': '/usr/bin/pv',
  'printf ': '/usr/bin/printf',
  'df ': '/usr/bin/df',
  'test -f /usr/share/virtio-win': '/usr/bin/test',
  'find /mnt/hyperv ': '/usr/bin/find',
  'mount -t cifs ': '/usr/bin/mount',
  'umount /mnt/hyperv': '/usr/bin/umount',
  'mountpoint ': '/usr/bin/mountpoint',
  'ovs-vsctl ': '/usr/bin/ovs-vsctl',
  'ovs-ofctl ': '/usr/bin/ovs-ofctl',
  'ip -o link': '/usr/sbin/ip',
  'ip link': '/usr/sbin/ip'
  // 'for br in $(ovs-vsctl list-br)' intentionally missing — shell-wrapped.
}

const SUDO_USER = 'proxcenter'

function escapeSudoersLine(s: string): string {
  return s.replace(/[\r\n]/g, ' ')
}

export function buildSudoersTemplate(categories: AllowlistCategoryShape[]): { body: string; shellWrappedCount: number } {
  const lines: string[] = [
    '# /etc/sudoers.d/proxcenter',
    '# Generated by ProxCenter (/settings?tab=ssh-commands).',
    '# Validate with: visudo -c -f /etc/sudoers.d/proxcenter',
    `Defaults:${SUDO_USER} !requiretty`,
    ''
  ]

  let shellWrappedCount = 0

  for (const cat of categories) {
    const byPath = new Map<string, string[]>()
    for (const cmd of cat.commands) {
      const path = executablePathByPrefix[cmd.prefix]
      if (!path) {
        shellWrappedCount++
        continue
      }
      if (!byPath.has(path)) byPath.set(path, [])
      byPath.get(path)!.push(cmd.prefix)
    }

    if (byPath.size === 0) continue

    lines.push(`# ${escapeSudoersLine(cat.label)}`)
    const paths = Array.from(byPath.keys()).sort()
    lines.push(`${SUDO_USER} ALL=(ALL) NOPASSWD: ${paths.join(', ')}`)
    lines.push('')
  }

  if (shellWrappedCount > 0) {
    lines.push('# Shell-wrapped commands (e.g. for-loop over OVS bridges for sFlow config).')
    lines.push('# Remove this line to disable shell-wrapped features such as Network Flows sFlow enable.')
    lines.push(`${SUDO_USER} ALL=(ALL) NOPASSWD: /bin/sh -c *`)
    lines.push('')
  }

  return { body: lines.join('\n'), shellWrappedCount }
}

export function buildInstallCommand(body: string): string {
  return `cat > /etc/sudoers.d/proxcenter <<'EOF'\n${body}\nEOF\nchmod 440 /etc/sudoers.d/proxcenter\nvisudo -c -f /etc/sudoers.d/proxcenter`
}
