// GENERATED by scripts/extract-cis-safeguards.ts — do not edit by hand.
// Input (pinned): scripts/cis-controls-v8.1-safeguards.json — identifiers and
// short titles only. CIS descriptive text is copyright Center for Internet
// Security and is NOT reproduced here.
// Authority:  https://www.cisecurity.org/controls/cis-controls-list
// Extracted:  2026-08-05, from the public CIS Controls Navigator listing.
// Family is the parent control, zero-padded, so that the localeCompare sort in
// assessFramework yields numeric order (04 before 12) in the UI and the PDF.
import type { FrameworkControl } from './types'

export const CIS_CONTROLS_V8_1_CONTROLS: FrameworkControl[] = [
    {
      "id": "1.1",
      "title": "Establish and Maintain Detailed Enterprise Asset Inventory",
      "family": "01 Inventory and Control of Enterprise Assets"
    },
    {
      "id": "1.2",
      "title": "Address Unauthorized Assets",
      "family": "01 Inventory and Control of Enterprise Assets"
    },
    {
      "id": "1.3",
      "title": "Utilize an Active Discovery Tool",
      "family": "01 Inventory and Control of Enterprise Assets"
    },
    {
      "id": "1.4",
      "title": "Use Dynamic Host Configuration Protocol (DHCP) Logging to Update Enterprise Asset Inventory",
      "family": "01 Inventory and Control of Enterprise Assets"
    },
    {
      "id": "1.5",
      "title": "Use a Passive Asset Discovery Tool",
      "family": "01 Inventory and Control of Enterprise Assets"
    },
    {
      "id": "2.1",
      "title": "Establish and Maintain a Software Inventory",
      "family": "02 Inventory and Control of Software Assets"
    },
    {
      "id": "2.2",
      "title": "Ensure Authorized Software is Currently Supported",
      "family": "02 Inventory and Control of Software Assets"
    },
    {
      "id": "2.3",
      "title": "Address Unauthorized Software",
      "family": "02 Inventory and Control of Software Assets"
    },
    {
      "id": "2.4",
      "title": "Utilize Automated Software Inventory Tools",
      "family": "02 Inventory and Control of Software Assets"
    },
    {
      "id": "2.5",
      "title": "Allowlist Authorized Software",
      "family": "02 Inventory and Control of Software Assets"
    },
    {
      "id": "2.6",
      "title": "Allowlist Authorized Libraries",
      "family": "02 Inventory and Control of Software Assets"
    },
    {
      "id": "2.7",
      "title": "Allowlist Authorized Scripts",
      "family": "02 Inventory and Control of Software Assets"
    },
    {
      "id": "3.1",
      "title": "Establish and Maintain a Data Management Process",
      "family": "03 Data Protection"
    },
    {
      "id": "3.2",
      "title": "Establish and Maintain a Data Inventory",
      "family": "03 Data Protection"
    },
    {
      "id": "3.3",
      "title": "Configure Data Access Control Lists",
      "family": "03 Data Protection"
    },
    {
      "id": "3.4",
      "title": "Enforce Data Retention",
      "family": "03 Data Protection"
    },
    {
      "id": "3.5",
      "title": "Securely Dispose of Data",
      "family": "03 Data Protection"
    },
    {
      "id": "3.6",
      "title": "Encrypt Data on End-User Devices",
      "family": "03 Data Protection"
    },
    {
      "id": "3.7",
      "title": "Establish and Maintain a Data Classification Scheme",
      "family": "03 Data Protection"
    },
    {
      "id": "3.8",
      "title": "Document Data Flows",
      "family": "03 Data Protection"
    },
    {
      "id": "3.9",
      "title": "Encrypt Data on Removable Media",
      "family": "03 Data Protection"
    },
    {
      "id": "3.10",
      "title": "Encrypt Sensitive Data in Transit",
      "family": "03 Data Protection"
    },
    {
      "id": "3.11",
      "title": "Encrypt Sensitive Data at Rest",
      "family": "03 Data Protection"
    },
    {
      "id": "3.12",
      "title": "Segment Data Processing and Storage Based on Sensitivity",
      "family": "03 Data Protection"
    },
    {
      "id": "3.13",
      "title": "Deploy a Data Loss Prevention Solution",
      "family": "03 Data Protection"
    },
    {
      "id": "3.14",
      "title": "Log Sensitive Data Access",
      "family": "03 Data Protection"
    },
    {
      "id": "4.1",
      "title": "Establish and Maintain a Secure Configuration Process",
      "family": "04 Secure Configuration of Enterprise Assets and Software"
    },
    {
      "id": "4.2",
      "title": "Establish and Maintain a Secure Configuration Process for Network Infrastructure",
      "family": "04 Secure Configuration of Enterprise Assets and Software"
    },
    {
      "id": "4.3",
      "title": "Configure Automatic Session Locking on Enterprise Assets",
      "family": "04 Secure Configuration of Enterprise Assets and Software"
    },
    {
      "id": "4.4",
      "title": "Implement and Manage a Firewall on Servers",
      "family": "04 Secure Configuration of Enterprise Assets and Software"
    },
    {
      "id": "4.5",
      "title": "Implement and Manage a Firewall on End-User Devices",
      "family": "04 Secure Configuration of Enterprise Assets and Software"
    },
    {
      "id": "4.6",
      "title": "Securely Manage Enterprise Assets and Software",
      "family": "04 Secure Configuration of Enterprise Assets and Software"
    },
    {
      "id": "4.7",
      "title": "Manage Default Accounts on Enterprise Assets and Software",
      "family": "04 Secure Configuration of Enterprise Assets and Software"
    },
    {
      "id": "4.8",
      "title": "Uninstall or Disable Unnecessary Services on Enterprise Assets and Software",
      "family": "04 Secure Configuration of Enterprise Assets and Software"
    },
    {
      "id": "4.9",
      "title": "Configure Trusted DNS Servers on Enterprise Assets",
      "family": "04 Secure Configuration of Enterprise Assets and Software"
    },
    {
      "id": "4.10",
      "title": "Enforce Automatic Device Lockout on Portable End-User Devices",
      "family": "04 Secure Configuration of Enterprise Assets and Software"
    },
    {
      "id": "4.11",
      "title": "Enforce Remote Wipe Capability on Portable End-User Devices",
      "family": "04 Secure Configuration of Enterprise Assets and Software"
    },
    {
      "id": "4.12",
      "title": "Separate Enterprise Workspaces on Mobile End-User Devices",
      "family": "04 Secure Configuration of Enterprise Assets and Software"
    },
    {
      "id": "5.1",
      "title": "Establish and Maintain an Inventory of Accounts",
      "family": "05 Account Management"
    },
    {
      "id": "5.2",
      "title": "Use Unique Passwords",
      "family": "05 Account Management"
    },
    {
      "id": "5.3",
      "title": "Disable Dormant Accounts",
      "family": "05 Account Management"
    },
    {
      "id": "5.4",
      "title": "Restrict Administrator Privileges to Dedicated Administrator Accounts",
      "family": "05 Account Management"
    },
    {
      "id": "5.5",
      "title": "Establish and Maintain an Inventory of Service Accounts",
      "family": "05 Account Management"
    },
    {
      "id": "5.6",
      "title": "Centralize Account Management",
      "family": "05 Account Management"
    },
    {
      "id": "6.1",
      "title": "Establish an Access Granting Process",
      "family": "06 Access Control Management"
    },
    {
      "id": "6.2",
      "title": "Establish an Access Revoking Process",
      "family": "06 Access Control Management"
    },
    {
      "id": "6.3",
      "title": "Require MFA for Externally-Exposed Applications",
      "family": "06 Access Control Management"
    },
    {
      "id": "6.4",
      "title": "Require MFA for Remote Network Access",
      "family": "06 Access Control Management"
    },
    {
      "id": "6.5",
      "title": "Require MFA for Administrative Access",
      "family": "06 Access Control Management"
    },
    {
      "id": "6.6",
      "title": "Establish and Maintain an Inventory of Authentication and Authorization Systems",
      "family": "06 Access Control Management"
    },
    {
      "id": "6.7",
      "title": "Centralize Access Control",
      "family": "06 Access Control Management"
    },
    {
      "id": "6.8",
      "title": "Define and Maintain Role-Based Access Control",
      "family": "06 Access Control Management"
    },
    {
      "id": "7.1",
      "title": "Establish and Maintain a Vulnerability Management Process",
      "family": "07 Continuous Vulnerability Management"
    },
    {
      "id": "7.2",
      "title": "Establish and Maintain a Remediation Process",
      "family": "07 Continuous Vulnerability Management"
    },
    {
      "id": "7.3",
      "title": "Perform Automated Operating System Patch Management",
      "family": "07 Continuous Vulnerability Management"
    },
    {
      "id": "7.4",
      "title": "Perform Automated Application Patch Management",
      "family": "07 Continuous Vulnerability Management"
    },
    {
      "id": "7.5",
      "title": "Perform Automated Vulnerability Scans of Internal Enterprise Assets",
      "family": "07 Continuous Vulnerability Management"
    },
    {
      "id": "7.6",
      "title": "Perform Automated Vulnerability Scans of Externally-Exposed Enterprise Assets",
      "family": "07 Continuous Vulnerability Management"
    },
    {
      "id": "7.7",
      "title": "Remediate Detected Vulnerabilities",
      "family": "07 Continuous Vulnerability Management"
    },
    {
      "id": "8.1",
      "title": "Establish and Maintain an Audit Log Management Process",
      "family": "08 Audit Log Management"
    },
    {
      "id": "8.2",
      "title": "Collect Audit Logs",
      "family": "08 Audit Log Management"
    },
    {
      "id": "8.3",
      "title": "Ensure Adequate Audit Log Storage",
      "family": "08 Audit Log Management"
    },
    {
      "id": "8.4",
      "title": "Standardize Time Synchronization",
      "family": "08 Audit Log Management"
    },
    {
      "id": "8.5",
      "title": "Collect Detailed Audit Logs",
      "family": "08 Audit Log Management"
    },
    {
      "id": "8.6",
      "title": "Collect DNS Query Audit Logs",
      "family": "08 Audit Log Management"
    },
    {
      "id": "8.7",
      "title": "Collect URL Request Audit Logs",
      "family": "08 Audit Log Management"
    },
    {
      "id": "8.8",
      "title": "Collect Command-Line Audit Logs",
      "family": "08 Audit Log Management"
    },
    {
      "id": "8.9",
      "title": "Centralize Audit Logs",
      "family": "08 Audit Log Management"
    },
    {
      "id": "8.10",
      "title": "Retain Audit Logs",
      "family": "08 Audit Log Management"
    },
    {
      "id": "8.11",
      "title": "Conduct Audit Log Reviews",
      "family": "08 Audit Log Management"
    },
    {
      "id": "8.12",
      "title": "Collect Service Provider Logs",
      "family": "08 Audit Log Management"
    },
    {
      "id": "9.1",
      "title": "Ensure Use of Only Fully Supported Browsers and Email Clients",
      "family": "09 Email and Web Browser Protections"
    },
    {
      "id": "9.2",
      "title": "Use DNS Filtering Services",
      "family": "09 Email and Web Browser Protections"
    },
    {
      "id": "9.3",
      "title": "Maintain and Enforce Network-Based URL Filters",
      "family": "09 Email and Web Browser Protections"
    },
    {
      "id": "9.4",
      "title": "Restrict Unnecessary or Unauthorized Browser and Email Client Extensions",
      "family": "09 Email and Web Browser Protections"
    },
    {
      "id": "9.5",
      "title": "Implement DMARC",
      "family": "09 Email and Web Browser Protections"
    },
    {
      "id": "9.6",
      "title": "Block Unnecessary File Types",
      "family": "09 Email and Web Browser Protections"
    },
    {
      "id": "9.7",
      "title": "Deploy and Maintain Email Server Anti-Malware Protections",
      "family": "09 Email and Web Browser Protections"
    },
    {
      "id": "10.1",
      "title": "Deploy and Maintain Anti-Malware Software",
      "family": "10 Malware Defenses"
    },
    {
      "id": "10.2",
      "title": "Configure Automatic Anti-Malware Signature Updates",
      "family": "10 Malware Defenses"
    },
    {
      "id": "10.3",
      "title": "Disable Autorun and Autoplay for Removable Media",
      "family": "10 Malware Defenses"
    },
    {
      "id": "10.4",
      "title": "Configure Automatic Anti-Malware Scanning of Removable Media",
      "family": "10 Malware Defenses"
    },
    {
      "id": "10.5",
      "title": "Enable Anti-Exploitation Features",
      "family": "10 Malware Defenses"
    },
    {
      "id": "10.6",
      "title": "Centrally Manage Anti-Malware Software",
      "family": "10 Malware Defenses"
    },
    {
      "id": "10.7",
      "title": "Use Behavior-Based Anti-Malware Software",
      "family": "10 Malware Defenses"
    },
    {
      "id": "11.1",
      "title": "Establish and Maintain a Data Recovery Process",
      "family": "11 Data Recovery"
    },
    {
      "id": "11.2",
      "title": "Perform Automated Backups",
      "family": "11 Data Recovery"
    },
    {
      "id": "11.3",
      "title": "Protect Recovery Data",
      "family": "11 Data Recovery"
    },
    {
      "id": "11.4",
      "title": "Establish and Maintain an Isolated Instance of Recovery Data",
      "family": "11 Data Recovery"
    },
    {
      "id": "11.5",
      "title": "Test Data Recovery",
      "family": "11 Data Recovery"
    },
    {
      "id": "12.1",
      "title": "Ensure Network Infrastructure is Up-to-Date",
      "family": "12 Network Infrastructure Management"
    },
    {
      "id": "12.2",
      "title": "Establish and Maintain a Secure Network Architecture",
      "family": "12 Network Infrastructure Management"
    },
    {
      "id": "12.3",
      "title": "Securely Manage Network Infrastructure",
      "family": "12 Network Infrastructure Management"
    },
    {
      "id": "12.4",
      "title": "Establish and Maintain Architecture Diagram(s)",
      "family": "12 Network Infrastructure Management"
    },
    {
      "id": "12.5",
      "title": "Centralize Network Authentication, Authorization, and Auditing (AAA)",
      "family": "12 Network Infrastructure Management"
    },
    {
      "id": "12.6",
      "title": "Use of Secure Network Management and Communication Protocols",
      "family": "12 Network Infrastructure Management"
    },
    {
      "id": "12.7",
      "title": "Ensure Remote Devices Utilize a VPN and are Connecting to an Enterprise’s AAA Infrastructure",
      "family": "12 Network Infrastructure Management"
    },
    {
      "id": "12.8",
      "title": "Establish and Maintain Dedicated Computing Resources for All Administrative Work",
      "family": "12 Network Infrastructure Management"
    },
    {
      "id": "13.1",
      "title": "Centralize Security Event Alerting",
      "family": "13 Network Monitoring and Defense"
    },
    {
      "id": "13.2",
      "title": "Deploy a Host-Based Intrusion Detection Solution",
      "family": "13 Network Monitoring and Defense"
    },
    {
      "id": "13.3",
      "title": "Deploy a Network Intrusion Detection Solution",
      "family": "13 Network Monitoring and Defense"
    },
    {
      "id": "13.4",
      "title": "Perform Traffic Filtering Between Network Segments",
      "family": "13 Network Monitoring and Defense"
    },
    {
      "id": "13.5",
      "title": "Manage Access Control for Remote Assets",
      "family": "13 Network Monitoring and Defense"
    },
    {
      "id": "13.6",
      "title": "Collect Network Traffic Flow Logs",
      "family": "13 Network Monitoring and Defense"
    },
    {
      "id": "13.7",
      "title": "Deploy a Host-Based Intrusion Prevention Solution",
      "family": "13 Network Monitoring and Defense"
    },
    {
      "id": "13.8",
      "title": "Deploy a Network Intrusion Prevention Solution",
      "family": "13 Network Monitoring and Defense"
    },
    {
      "id": "13.9",
      "title": "Deploy Port-Level Access Control",
      "family": "13 Network Monitoring and Defense"
    },
    {
      "id": "13.10",
      "title": "Perform Application Layer Filtering",
      "family": "13 Network Monitoring and Defense"
    },
    {
      "id": "13.11",
      "title": "Tune Security Event Alerting Thresholds",
      "family": "13 Network Monitoring and Defense"
    },
    {
      "id": "14.1",
      "title": "Establish and Maintain a Security Awareness Program",
      "family": "14 Security Awareness and Skills Training"
    },
    {
      "id": "14.2",
      "title": "Train Workforce Members to Recognize Social Engineering Attacks",
      "family": "14 Security Awareness and Skills Training"
    },
    {
      "id": "14.3",
      "title": "Train Workforce Members on Authentication Best Practices",
      "family": "14 Security Awareness and Skills Training"
    },
    {
      "id": "14.4",
      "title": "Train Workforce on Data Handling Best Practices",
      "family": "14 Security Awareness and Skills Training"
    },
    {
      "id": "14.5",
      "title": "Train Workforce Members on Causes of Unintentional Data Exposure",
      "family": "14 Security Awareness and Skills Training"
    },
    {
      "id": "14.6",
      "title": "Train Workforce Members on Recognizing and Reporting Security Incidents",
      "family": "14 Security Awareness and Skills Training"
    },
    {
      "id": "14.7",
      "title": "Train Workforce on How to Identify and Report if Their Enterprise Assets are Missing Security Updates",
      "family": "14 Security Awareness and Skills Training"
    },
    {
      "id": "14.8",
      "title": "Train Workforce on the Dangers of Connecting to and Transmitting Enterprise Data Over Insecure Networks",
      "family": "14 Security Awareness and Skills Training"
    },
    {
      "id": "14.9",
      "title": "Conduct Role-Specific Security Awareness and Skills Training",
      "family": "14 Security Awareness and Skills Training"
    },
    {
      "id": "15.1",
      "title": "Establish and Maintain an Inventory of Service Providers",
      "family": "15 Service Provider Management"
    },
    {
      "id": "15.2",
      "title": "Establish and Maintain a Service Provider Management Policy",
      "family": "15 Service Provider Management"
    },
    {
      "id": "15.3",
      "title": "Classify Service Providers",
      "family": "15 Service Provider Management"
    },
    {
      "id": "15.4",
      "title": "Ensure Service Provider Contracts Include Security Requirements",
      "family": "15 Service Provider Management"
    },
    {
      "id": "15.5",
      "title": "Assess Service Providers",
      "family": "15 Service Provider Management"
    },
    {
      "id": "15.6",
      "title": "Monitor Service Providers",
      "family": "15 Service Provider Management"
    },
    {
      "id": "15.7",
      "title": "Securely Decommission Service Providers",
      "family": "15 Service Provider Management"
    },
    {
      "id": "16.1",
      "title": "Establish and Maintain a Secure Application Development Process",
      "family": "16 Application Software Security"
    },
    {
      "id": "16.2",
      "title": "Establish and Maintain a Process to Accept and Address Software Vulnerabilities",
      "family": "16 Application Software Security"
    },
    {
      "id": "16.3",
      "title": "Perform Root Cause Analysis on Security Vulnerabilities",
      "family": "16 Application Software Security"
    },
    {
      "id": "16.4",
      "title": "Establish and Manage an Inventory of Third-Party Software Components",
      "family": "16 Application Software Security"
    },
    {
      "id": "16.5",
      "title": "Use Up-to-Date and Trusted Third-Party Software Components",
      "family": "16 Application Software Security"
    },
    {
      "id": "16.6",
      "title": "Establish and Maintain a Severity Rating System and Process for Application Vulnerabilities",
      "family": "16 Application Software Security"
    },
    {
      "id": "16.7",
      "title": "Use Standard Hardening Configuration Templates for Application Infrastructure",
      "family": "16 Application Software Security"
    },
    {
      "id": "16.8",
      "title": "Separate Production and Non-Production Systems",
      "family": "16 Application Software Security"
    },
    {
      "id": "16.9",
      "title": "Train Developers in Application Security Concepts and Secure Coding",
      "family": "16 Application Software Security"
    },
    {
      "id": "16.10",
      "title": "Apply Secure Design Principles in Application Architectures",
      "family": "16 Application Software Security"
    },
    {
      "id": "16.11",
      "title": "Leverage Vetted Modules or Services for Application Security Components",
      "family": "16 Application Software Security"
    },
    {
      "id": "16.12",
      "title": "Implement Code-Level Security Checks",
      "family": "16 Application Software Security"
    },
    {
      "id": "16.13",
      "title": "Conduct Application Penetration Testing",
      "family": "16 Application Software Security"
    },
    {
      "id": "16.14",
      "title": "Conduct Threat Modeling",
      "family": "16 Application Software Security"
    },
    {
      "id": "17.1",
      "title": "Designate Personnel to Manage Incident Handling",
      "family": "17 Incident Response Management"
    },
    {
      "id": "17.2",
      "title": "Establish and Maintain Contact Information for Reporting Security Incidents",
      "family": "17 Incident Response Management"
    },
    {
      "id": "17.3",
      "title": "Establish and Maintain an Enterprise Process for Reporting Incidents",
      "family": "17 Incident Response Management"
    },
    {
      "id": "17.4",
      "title": "Establish and Maintain an Incident Response Process",
      "family": "17 Incident Response Management"
    },
    {
      "id": "17.5",
      "title": "Assign Key Roles and Responsibilities",
      "family": "17 Incident Response Management"
    },
    {
      "id": "17.6",
      "title": "Define Mechanisms for Communicating During Incident Response",
      "family": "17 Incident Response Management"
    },
    {
      "id": "17.7",
      "title": "Conduct Routine Incident Response Exercises",
      "family": "17 Incident Response Management"
    },
    {
      "id": "17.8",
      "title": "Conduct Post-Incident Reviews",
      "family": "17 Incident Response Management"
    },
    {
      "id": "17.9",
      "title": "Establish and Maintain Security Incident Thresholds",
      "family": "17 Incident Response Management"
    },
    {
      "id": "18.1",
      "title": "Establish and Maintain a Penetration Testing Program",
      "family": "18 Penetration Testing"
    },
    {
      "id": "18.2",
      "title": "Perform Periodic External Penetration Tests",
      "family": "18 Penetration Testing"
    },
    {
      "id": "18.3",
      "title": "Remediate Penetration Test Findings",
      "family": "18 Penetration Testing"
    },
    {
      "id": "18.4",
      "title": "Validate Security Measures",
      "family": "18 Penetration Testing"
    },
    {
      "id": "18.5",
      "title": "Perform Periodic Internal Penetration Tests",
      "family": "18 Penetration Testing"
    }
  ]
